name: Adds labels

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add labels
        run: |
          set -x
          result=""

          # Sleep to ensure all pipelines start.
          sleep 10
          echo "Waiting while CI pipelines complete"

          until [[ $result -eq 1 ]]; do
            result=$(
              gh pr checks $PR_NUMBER \
                --json "bucket" \
                --jq "[.[] | select(.bucket == \"pending\")] | length"
              )
            
            sleep 15
          done

          echo "Evaluating whether there were any CI failures"

          result=$(
            gh pr checks $PR_NUMBER \
              --json "bucket" \
              --jq "isempty(.[] | select(.bucket == \"fail\"))"
          )

          if [[ $result == "true" ]]; then
            gh pr edit $PR_NUMBER --remove-label "S-awaiting-CI"
          else
            gh pr edit $PR_NUMBER --add-label "S-awaiting-CI"
          fi
